In [2]:
# one dimensional NumPy array

import numpy as np

i = np.array([1,2,3,4,5])

print(i) 

[1 2 3 4 5]


In [3]:
for j in i:
    print(j)

1
2
3
4
5


In [4]:
#  access Numpy 1D array value one by one with loop…

import numpy as np

i = np.array([1,2,3,4,5])

for j in i:
    print(j)

1
2
3
4
5


In [5]:
# two dimensional NumPy array

import numpy as np
i = np.array([
[10, 20, 30],
[40, 50, 60],
[70, 80, 90]
])
print(i)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
# check the type of ndarray and num of dimentions…

import numpy as np
i = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print()

print(type(i), " ", i.ndim)


<class 'numpy.ndarray'>   2


In [7]:
# check the size of the NumPy array

import numpy as np

i = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [7, 8, 9],
])

print(i.size)

12


In [8]:
# check the shape of ndarray

import numpy as np

i = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [7, 8, 9],
])

print(i.shape)

(4, 3)


In [9]:
# One metrics using python NumPy

import numpy as np

np.ones((4,4), dtype = int)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
# Zeros metrics use NumPy

np.zeros((3, 3), dtype = int)



array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Empty metrics

import numpy as np

np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.11062617e-321, 1.78021391e-306,
        1.24611470e-306]])

In [15]:
# Convert 1D array to multidimensional array

import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

j = np.reshape(i, (3,4))

print(j)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
# Convert multidimensional array in one dimensional

import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

j = np.reshape(i, (3,4))

k = j.flatten()

print(k)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
import numpy as np

i = np.arange(1,10).reshape(3,3)

j = np.arange(1,10).reshape(3,3)

print(i)

print()

print(j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
import numpy as np

i = np.arange(1,21).reshape(4,5)

j = np.arange(1,10).reshape(3,3)

print(i)

print()

print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Addition of Two Numpy Array

import numpy as np

i = np.arange(1,10).reshape(3,3)

j = np.arange(1,10).reshape(3,3)

i+j

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
import numpy as np

i = np.arange(1,10).reshape(3,3)

j = np.arange(1,10).reshape(3,3)

np.add(i, i)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [21]:
# Calculate Mean 

import numpy as np

i = np.arange(1,10).reshape(3,3)

j = np.arange(1,21).reshape(4,5)

print(np.mean(i))

print(np.mean(j))


5.0
10.5


# ML Project Setup

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# convert time in date time data type
from dateutil import parser


In [24]:
appData = pd.read_csv("D:\\data set\\appData.csv")

appData.head(20)

user               first_open  dayofweek       hour  age  \
0   235136  2012-12-27 02:14:51.273          3   02:00:00   23   
1   333588  2012-12-02 01:16:00.905          6   01:00:00   24   
2   254414  2013-03-19 19:19:09.157          1   19:00:00   23   
3   234192  2013-07-05 16:08:46.354          4   16:00:00   28   
4    51549  2013-02-26 18:50:48.661          1   18:00:00   31   
5    56480  2013-04-03 09:58:15.752          2   09:00:00   20   
6   144649  2012-12-25 02:33:18.461          1   02:00:00   35   
7   249366  2012-12-11 03:07:49.875          1   03:00:00   26   
8   372004  2013-03-20 14:22:01.569          2   14:00:00   29   
9   338013  2013-04-26 18:22:16.013          4   18:00:00   26   
10   43555  2013-05-14 04:48:27.597          1   04:00:00   39   
11  317454  2013-05-28 11:07:07.358          1   11:00:00   32   
12  205375  2012-12-17 06:28:45.903          0   06:00:00   25   
13  307608  2013-05-25 19:52:31.798          5   19:00:00   23   
14  359855  2013-02-18 04:48:48.912          0   04:00:00   17   
15  284938  2013-02-02 18:41:35.724          5   18:00:00   25   
16  235143  2013-07-07 16:07:35.057          6   16:00:00   21   
17  141402  2013-02-02 21:12:46.888          5   21:00:00   55   
18  257945  2013-05-10 05:59:43.405          4   05:00:00   32   
19   54931  2013-07-06 17:34:46.439          5   17:00:00   25   

                                          screen_list  numscreens  minigame  \
0   idscreen,joinscreen,Cycle,product_review,ScanP...          15         0   
1   joinscreen,product_review,product_review2,Scan...          13         0   
2                                   Splash,Cycle,Loan           3         0   
3   product_review,Home,product_review,Loan3,Finan...          40         0   
4   idscreen,joinscreen,Cycle,Credit3Container,Sca...          32         0   
5   idscreen,Cycle,Home,ScanPreview,VerifyPhone,Ve...          14         0   
6          product_review,product_review2,ScanPreview           3         0   
7   Splash,Cycle,Home,Credit3Container,Credit3Dash...          41         0   
8   product_review,product_review2,ScanPreview,Ver...          33         1   
9   Home,Loan2,product_review,product_review,produ...          19         0   
10  Splash,idscreen,Home,RewardsContainer,Settings...          14         0   
11  product_review,Home,Loan2,Credit3Container,Ver...          25         1   
12  idscreen,joinscreen,Cycle,product_review,produ...          11         0   
13           Alerts,ProfilePage,Home,Credit3Container           4         0   
14  joinscreen,product_review,product_review2,Scan...           9         0   
15  idscreen,joinscreen,Cycle,Loan2,product_review...          26         1   
16  product_review,product_review,product_review,p...           6         0   
17  joinscreen,Cycle,product_review,Loan2,product_...          20         0   
18  Splash,product_review,Home,Loan2,product_revie...          15         0   
19  idscreen,Loan3,product_review,product_review,Home           5         0   

    used_premium_feature  enrolled            enrolled_date  liked  
0                      0         0                      NaN      0  
1                      0         0                      NaN      0  
2                      1         0                      NaN      1  
3                      0         1  2013-07-05 16:11:49.513      0  
4                      0         1  2013-02-26 18:56:37.841      1  
5                      0         1  2013-04-03 09:59:03.291      0  
6                      0         0                      NaN      0  
7                      1         0                      NaN      0  
8                      1         1  2013-04-27 22:24:54.542      0  
9                      0         1  2013-04-26 18:31:58.923      0  
10                     0         1  2013-05-15 21:02:17.200      0  
11                     1         0                      NaN      0  
12                     0         0                      NaN   

In [25]:
appData = pd.read_csv("D:\\data set\\appData.csv")

appData.head(10)

user               first_open  dayofweek       hour  age  \
0  235136  2012-12-27 02:14:51.273          3   02:00:00   23   
1  333588  2012-12-02 01:16:00.905          6   01:00:00   24   
2  254414  2013-03-19 19:19:09.157          1   19:00:00   23   
3  234192  2013-07-05 16:08:46.354          4   16:00:00   28   
4   51549  2013-02-26 18:50:48.661          1   18:00:00   31   
5   56480  2013-04-03 09:58:15.752          2   09:00:00   20   
6  144649  2012-12-25 02:33:18.461          1   02:00:00   35   
7  249366  2012-12-11 03:07:49.875          1   03:00:00   26   
8  372004  2013-03-20 14:22:01.569          2   14:00:00   29   
9  338013  2013-04-26 18:22:16.013          4   18:00:00   26   

                                         screen_list  numscreens  minigame  \
0  idscreen,joinscreen,Cycle,product_review,ScanP...          15         0   
1  joinscreen,product_review,product_review2,Scan...          13         0   
2                                  Splash,Cycle,Loan           3         0   
3  product_review,Home,product_review,Loan3,Finan...          40         0   
4  idscreen,joinscreen,Cycle,Credit3Container,Sca...          32         0   
5  idscreen,Cycle,Home,ScanPreview,VerifyPhone,Ve...          14         0   
6         product_review,product_review2,ScanPreview           3         0   
7  Splash,Cycle,Home,Credit3Container,Credit3Dash...          41         0   
8  product_review,product_review2,ScanPreview,Ver...          33         1   
9  Home,Loan2,product_review,product_review,produ...          19         0   

   used_premium_feature  enrolled            enrolled_date  liked  
0                     0         0                      NaN      0  
1                     0         0                      NaN      0  
2                     1         0                      NaN      1  
3                     0         1  2013-07-05 16:11:49.513      0  
4                     0         1  2013-02-26 18:56:37.841      1  
5                     0         1  2013-04-03 09:59:03.291      0  
6                     0         0                      NaN      0  
7                     1         0                      NaN      0  
8                     1         1  2013-04-27 22:24:54.542      0  
9                     0         1  2013-04-26 18:31:58.923      0

In [26]:
appData.tail() 

user               first_open  dayofweek       hour  age  \
49995  222774  2013-05-09 13:46:17.871          3   13:00:00   32   
49996  169179  2013-04-09 00:05:17.823          1   00:00:00   35   
49997  302367  2013-02-20 22:41:51.165          2   22:00:00   39   
49998  324905  2013-04-28 12:33:04.288          6   12:00:00   27   
49999   27047  2012-12-14 01:22:44.638          4   01:00:00   25   

                                             screen_list  numscreens  \
49995  Splash,Home,ScanPreview,VerifyPhone,VerifySSN,...          13   
49996                 Cycle,Splash,Home,RewardsContainer           4   
49997  joinscreen,product_review,product_review2,Scan...          25   
49998  Cycle,Home,product_review,product_review,produ...          26   
49999  product_review,ScanPreview,VerifyDateOfBirth,V...          26   

       minigame  used_premium_feature  enrolled            enrolled_date  \
49995         0                     0         1  2013-05-09 13:47:52.875   
49996         0                     1         0                      NaN   
49997         0                     0         0                      NaN   
49998         0                     0         1  2013-04-28 12:35:38.709   
49999         0                     0         0                      NaN   

       liked  
49995      0  
49996      0  
49997      0  
49998      0  
49999      1

In [27]:
appData.tail(10) 

user               first_open  dayofweek       hour  age  \
49990  179308  2013-05-25 17:30:47.675          5   17:00:00   20   
49991   85532  2013-02-01 22:33:59.502          4   22:00:00   45   
49992   96155  2013-02-03 15:41:52.059          6   15:00:00   50   
49993  343026  2012-11-24 02:02:56.012          5   02:00:00   28   
49994   90813  2013-02-25 19:35:12.691          0   19:00:00   36   
49995  222774  2013-05-09 13:46:17.871          3   13:00:00   32   
49996  169179  2013-04-09 00:05:17.823          1   00:00:00   35   
49997  302367  2013-02-20 22:41:51.165          2   22:00:00   39   
49998  324905  2013-04-28 12:33:04.288          6   12:00:00   27   
49999   27047  2012-12-14 01:22:44.638          4   01:00:00   25   

                                             screen_list  numscreens  \
49990  Splash,idscreen,Cycle,Home,product_review,prod...           8   
49991  Splash,Cycle,Home,Loan2,Loan1,MLWebView,Instit...          30   
49992  idscreen,joinscreen,product_review,product_rev...          28   
49993  joinscreen,product_review,product_review2,Scan...           4   
49994  idscreen,joinscreen,Cycle,product_review,produ...          25   
49995  Splash,Home,ScanPreview,VerifyPhone,VerifySSN,...          13   
49996                 Cycle,Splash,Home,RewardsContainer           4   
49997  joinscreen,product_review,product_review2,Scan...          25   
49998  Cycle,Home,product_review,product_review,produ...          26   
49999  product_review,ScanPreview,VerifyDateOfBirth,V...          26   

       minigame  used_premium_feature  enrolled            enrolled_date  \
49990         0                     0         1  2013-05-26 06:33:54.237   
49991         1                     1         1  2013-02-01 22:35:36.750   
49992         0                     0         1  2013-02-03 15:43:43.163   
49993         0                     0         0                      NaN   
49994         0                     0         1  2013-02-25 19:36:56.082   
49995         0                     0         1  2013-05-09 13:47:52.875   
49996         0                     1         0                      NaN   
49997         0                     0         0                      NaN   
49998         0                     0         1  2013-04-28 12:35:38.709   
49999         0                     0         0                      NaN   

       liked  
49990      1  
49991      0  
49992      0  
49993      1  
49994      0  
49995      0  
49996      0  
49997      0  
49998      0  
49999      1

In [28]:
for i in [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]:
    print(appData.loc[i,'screen_list'], "\n")

joinscreen,product_review,product_review2,ScanPreview,VerifyDateOfBirth,location,VerifyCountry,VerifyPhone,VerifyToken,Institutions,Loan2 

Splash,Cycle,Loan 

product_review,Home,product_review,Loan3,Finances,Credit3,ReferralContainer,Leaderboard,Rewards,RewardDetail,ScanPreview,location,VerifyDateOfBirth,VerifyPhone,VerifySSN,Credit1,Credit2 

idscreen,joinscreen,Cycle,Credit3Container,ScanPreview,VerifyPhone,VerifySSN,Credit1,Loan2,Home,Institutions,SelectInstitution,BankVerification,ReferralContainer,product_review,product_review2,VerifyCountry,VerifyToken,product_review 

idscreen,Cycle,Home,ScanPreview,VerifyPhone,VerifySSN,Credit1,Credit3Dashboard,Loan2,Institutions,product_review,product_review,product_review3 

product_review,product_review2,ScanPreview 

Splash,Cycle,Home,Credit3Container,Credit3Dashboard,Loan2,product_review,product_review2,ScanPreview,VerifyCountry,VerifyPhone,VerifyToken,product_review,product_review,SelectInstitution,BankVerification,TransactionList 

pro

In [29]:
for i in range(1,26):
    print(appData.loc[i,'screen_list'], "\n")

joinscreen,product_review,product_review2,ScanPreview,VerifyDateOfBirth,location,VerifyCountry,VerifyPhone,VerifyToken,Institutions,Loan2 

Splash,Cycle,Loan 

product_review,Home,product_review,Loan3,Finances,Credit3,ReferralContainer,Leaderboard,Rewards,RewardDetail,ScanPreview,location,VerifyDateOfBirth,VerifyPhone,VerifySSN,Credit1,Credit2 

idscreen,joinscreen,Cycle,Credit3Container,ScanPreview,VerifyPhone,VerifySSN,Credit1,Loan2,Home,Institutions,SelectInstitution,BankVerification,ReferralContainer,product_review,product_review2,VerifyCountry,VerifyToken,product_review 

idscreen,Cycle,Home,ScanPreview,VerifyPhone,VerifySSN,Credit1,Credit3Dashboard,Loan2,Institutions,product_review,product_review,product_review3 

product_review,product_review2,ScanPreview 

Splash,Cycle,Home,Credit3Container,Credit3Dashboard,Loan2,product_review,product_review2,ScanPreview,VerifyCountry,VerifyPhone,VerifyToken,product_review,product_review,SelectInstitution,BankVerification,TransactionList 

pro

In [30]:
appData.isnull().sum()

user                        0
first_open                  0
dayofweek                   0
hour                        0
age                         0
screen_list                 0
numscreens                  0
minigame                    0
used_premium_feature        0
enrolled                    0
enrolled_date           18926
liked                       0
dtype: int64

In [31]:
appData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   user                  50000 non-null  int64 
 1   first_open            50000 non-null  object
 2   dayofweek             50000 non-null  int64 
 3   hour                  50000 non-null  object
 4   age                   50000 non-null  int64 
 5   screen_list           50000 non-null  object
 6   numscreens            50000 non-null  int64 
 7   minigame              50000 non-null  int64 
 8   used_premium_feature  50000 non-null  int64 
 9   enrolled              50000 non-null  int64 
 10  enrolled_date         31074 non-null  object
 11  liked                 50000 non-null  int64 
dtypes: int64(8), object(4)
memory usage: 4.6+ MB


In [32]:
appData.isnull().sum().sum()

18926

In [33]:
appData.describe()

user     dayofweek          age    numscreens      minigame  \
count   50000.000000  50000.000000  50000.00000  50000.000000  50000.000000   
mean   186889.729900      3.029860     31.72436     21.095900      0.107820   
std    107768.520361      2.031997     10.80331     15.728812      0.310156   
min        13.000000      0.000000     16.00000      1.000000      0.000000   
25%     93526.750000      1.000000     24.00000     10.000000      0.000000   
50%    187193.500000      3.000000     29.00000     18.000000      0.000000   
75%    279984.250000      5.000000     37.00000     28.000000      0.000000   
max    373662.000000      6.000000    101.00000    325.000000      1.000000   

       used_premium_feature      enrolled         liked  
count          50000.000000  50000.000000  50000.000000  
mean               0.172020      0.621480      0.165000  
std                0.377402      0.485023      0.371184  
min                0.000000      0.000000      0.000000  
25%                0.000000      0.000000      0.000000  
50%                0.000000      1.000000      0.000000  
75%                0.000000      1.000000      0.000000  
max                1.000000      1.000000      1.000000

In [34]:
sub_features = appData.columns
for i in sub_features:
    print("""Unique value of {} \n {} \n........................\n""".format(i, appData[i].unique(),len(appData[i].unique())))

Unique value of user 
 [235136 333588 254414 ... 302367 324905  27047] 
........................

Unique value of first_open 
 ['2012-12-27 02:14:51.273' '2012-12-02 01:16:00.905'
 '2013-03-19 19:19:09.157' ... '2013-02-20 22:41:51.165'
 '2013-04-28 12:33:04.288' '2012-12-14 01:22:44.638'] 
........................

Unique value of dayofweek 
 [3 6 1 4 2 0 5] 
........................

Unique value of hour 
 [' 02:00:00' ' 01:00:00' ' 19:00:00' ' 16:00:00' ' 18:00:00' ' 09:00:00'
 ' 03:00:00' ' 14:00:00' ' 04:00:00' ' 11:00:00' ' 06:00:00' ' 21:00:00'
 ' 05:00:00' ' 17:00:00' ' 20:00:00' ' 00:00:00' ' 22:00:00' ' 10:00:00'
 ' 08:00:00' ' 15:00:00' ' 13:00:00' ' 23:00:00' ' 12:00:00' ' 07:00:00'] 
........................

Unique value of age 
 [ 23  24  28  31  20  35  26  29  39  32  25  17  21  55  38  27  48  37
  22  36  30  58  40  33  57  19  45  34  46  56  42  43  41  47  18  53
  44  49  60  50  52  62  63  16  54  70  51  69  68  59  76  75  66  61
  72  65  90  64  67  73  7